### ISSUE TITLE
Encountered problems while solving:   - nothing provides requested tensorflow ==2.2.0 gpu_py37h1a511ff_0

### ISSUE THREAD

**Issue by bryandunn614** [tom-andersson/icenet-paper#5] opened 2023-05-15 03:02 UTC
Hello:
     I am following your tutorial,however when I use mamba to create the environment using the following commands
    mamba env create --file environment.yml
    it shows that:
    
![image](https://github.com/tom-andersson/icenet-paper/assets/129260579/4bf4b6a7-b2b2-4c65-b0c9-9198d3910bea)

  for the command:mamba env create --file environment.locked.yml
![image](https://github.com/tom-andersson/icenet-paper/assets/129260579/ef964e94-ebaa-4d0d-bf8d-d93fa42fed3f)

Do you know how to solve it,I jst follow the guidance step by step,thank you

**Comment by bryandunn614** [comment] 2023-05-15 10:06
The above problem has been solved,I  just delete the tensorflow line in environment.yml and install tensorflow-gpu later in icenet environment.
Here is antoher problem,when I run the gen_masks.py,the error is:
OSError: [UT_OPEN_ARG] Failed to open UDUNITS-2 XML unit database: "b'No such file or directory'"
![image](https://github.com/tom-andersson/icenet-paper/assets/129260579/f9d13009-b142-4dc7-820b-75b180d985b3)
 
So do I need to download other dependency package?I set up the environment following the guidance

**Comment by JimCircadian** [comment] 2023-05-15 10:46
Hi @bryandunn614, I'll CC @tom-andersson as he maintains this repository directly, but looking at the [latest scitools iris](https://scitools-iris.readthedocs.io/en/latest/installing.html) documentation it's not tested on Windows (they seem to suggest the Windows Subsystem for Linux might work.) The error is coming from a `cf-units` which is part of scitools.

`icenet-paper` was developed specifically on Linux, so some of these pain points might be coming from the use of native Windows rather than the WSL, which is very much untested. My personal advice would be to try doing this using the WSL feature for Windows to do your installation (please let me know if you already are, but looking at your prompt it doesn't appear so! 😉)

**Comment by tom-andersson** [comment] 2023-05-15 13:31
Hi @bryandunn614, as @JimCircadian suggests, these errors are probably caused by using Windows, whereas the README states _"The guidelines below assume you're working in the command line of **a Unix-like machine** with a GPU."_

I will close this issue for now as I would prefer open issues to specifically relate to problems contained within the codebase rather than problems with people's local environments. If you switch to WSL or a Unix machine and still encounter issues then let us know here or in a new issue.

**Closed by tom-andersson** 2023-05-15 13:31 UTC

**Comment by bryandunn614** [comment] 2023-05-15 14:27
Thanks Jim and Tom, your quick replies  help me a lot, really appreciate it.

**Comment by bryandunn614** [comment] 2023-05-16 04:02
![image](https://github.com/tom-andersson/icenet-paper/assets/129260579/034de413-7c06-4931-b572-a8861d9317fe)

![屏幕截图 2023-05-16 135127](https://github.com/tom-andersson/icenet-paper/assets/129260579/cfaecd98-e3cb-4802-a7f1-cc3c40758ed6)

Hello @tom-andersson ,I am runing the download_seas5_forecasts_in_parallel.sh,however the project doesn't have a python file named download_seas5_data.py instead there is a file download_seas5_forecasts.py,when I using the bash to run the commands,it will say "download_seas5_data.py No such file" 
![image](https://github.com/tom-andersson/icenet-paper/assets/129260579/fbdfe04a-8491-4dba-8fde-16b0e71fc9ab)

I am wondering if there is a mistake,cause I have search the whole project.
There alos isn't a file named "biascorrect_seas5_data.py",
however the file name is "biascorrect_seas5_forecasts.py"

**Comment by tom-andersson** [comment] 2023-05-16 12:44
Thanks for catching this @bryandunn614, those were prior names for the scripts and the README wasn't updated. Fixed in https://github.com/tom-andersson/icenet-paper/commit/f63751993eba516130fd302a377f4c8a7f42f4fe
