### ISSUE TITLE
Why python3 icenet/download_cmip6_data.py  takes so much memory space to run

### ISSUE THREAD

**Issue by bryandunn614** [tom-andersson/icenet-paper#7] opened 2023-07-08 16:22 UTC
Hello I have run with another issue,when I run  download_cmip6_data_in_parallel.sh Ubuntu will kill all 5 commands with EC-Earth3 download.
So I  try to run the first command of  download_cmip6_data_in_parallel.sh to see what happend,just run this command:
python3 icenet/download_cmip6_data.py  --source_id EC-Earth3 --member_id r2i1p1f1 > logs/cmip6_download_logs/EC_r2i1p1f1.txt 2>&1 &

or equally directly run  download_cmip6_data.py with default:EC-Earth3 r2i1p1f1
At first when I run this program my memory usage is up to 80%(I have terminated almost all other processes)
Unfortunately the process is still killed by Ubuntu,when it comes to Generating video stage

My laptop memory is 2*8=16GB but still run out.Does that mean this project can only be running with a local machcine with memory larger(32GB or more?) or can only be trained on AWS or Azure(Clous Server) ?

**Comment by bryandunn614** [comment] 2023-07-08 16:39
The terminal message of running process is 
python3 icenet/download_cmip6_data.py

**_Downloading data for EC-Earth3, r2i1p1f1

siconca:searching ESGF... found historical,found ssp245,....
Generating video...48%
Killed_**

**Comment by tom-andersson** [comment] 2023-07-11 11:04
Hi @bryandunn614, note that you can prevent videos of the CMIP6 variables from being generated by changing this line to `False`:https://github.com/tom-andersson/icenet-paper/blob/4f5fb2789a77c04300f4c99bde51361d237c09d0/icenet/download_cmip6_data.py#L61

However, more generally, if you want to pre-train IceNet on the CMIP6 data then you will need to be working in the cloud with more memory than a laptop. If you are constrained to a laptop then I would skip the CMIP6 pre-training phase and just train on observational/reanalysis data. 

Unfortunately I don't have the capacity to address issues caused by hardware so I will close this issue.

**Closed by tom-andersson** 2023-07-11 11:04 UTC
